"""empty message

Revision ID: 4f927547fe25
Revises: 9847327a3dbf
Create Date: 2020-04-11 11:54:44.448771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f927547fe25'
down_revision = '9847327a3dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'timestamp')
    # ### end Alembic commands ###
