"""new fields in user model

Revision ID: 8a0d205de9c4
Revises: 2c01b76ae11a
Create Date: 2020-04-06 15:21:08.733290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0d205de9c4'
down_revision = '2c01b76ae11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('institution', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'institution')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
