"""empty message

Revision ID: b0c208ca3a5a
Revises: 8a0d205de9c4
Create Date: 2020-04-07 09:16:03.286262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c208ca3a5a'
down_revision = '8a0d205de9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('link', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'course', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', 'link')
    # ### end Alembic commands ###
