"""empty message

Revision ID: b22369b76725
Revises: 14b39b9b3b5e
Create Date: 2020-04-09 07:14:54.596106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22369b76725'
down_revision = '14b39b9b3b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('alias', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('max_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'max_score')
    op.drop_column('task', 'is_done')
    op.drop_table('student')
    # ### end Alembic commands ###
