"""empty message

Revision ID: c64541239ddb
Revises: b0c208ca3a5a
Create Date: 2020-04-07 09:20:48.787126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64541239ddb'
down_revision = 'b0c208ca3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('link', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'link')
    # ### end Alembic commands ###
