"""empty message

Revision ID: c7968cf4263b
Revises: da063b5adcd1
Create Date: 2020-04-16 13:53:08.293480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7968cf4263b'
down_revision = 'da063b5adcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_email')
    # ### end Alembic commands ###
